version: '3.8'
services:
  tt_dev_backend:
    build:
      context: ./backend/src
      dockerfile: Dockerfile.dev
    ports:
      - '80:3000'
    volumes:
      - ./backend/src:/app
      - /app/node_modules
    env_file:
      - ./backend/config/.env